{{- $gcsSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := "gcp-d193ca-prod-obps-backups-service-account-key" }}

{{- $secret := (lookup "v1" "Secret" "d193ca-prod" $secretName ) }}
{{- if $secret }}
{{- $gcsSecret = index $secret.data "credentials.json" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "test-backups.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  credentials: {{ $gcsSecret }}
