apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "test-backups.fullname" . }}
  labels: {{ include "test-backups.labels" . | nindent 4 }}
spec:
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - configMap:
            name: {{ template "test-backups.fullname" . }}-pgbackrest
        - secret:
            name: gcp-d193ca-prod-obps-backups-service-account-key
            items:
              - key: credentials
                path: gcs-key.json
      repo:
        name: repo1
        gcs:
          bucket: "d193ca-prod-obps-backups"
  image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres:ubi8-14.7-0
  metadata:
    labels: {{ include "test-backups.labels" . | nindent 6 }} 
  postgresVersion: 14
  instances:
    - name: pgha1
      replicas: 1
      # this is how you create a PDB - don't make a separate one yourself!
      minAvailable: 1
      # these resources are for the "database" container in the "obps-postgres-pgha1" set of pods
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      sidecars:
        # this stuff is for the "replication-cert-copy" container in the "obps-postgres-pgha1" set of pods
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Mi
        storageClassName: netapp-block-standard
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: {{ template "test-backups.fullname" . }} 
                    postgres-operator.crunchydata.com/instance-set: pgha1

  backups:
    pgbackrest:
      image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-pgbackrest:ubi8-2.41-4
      repos:
        - name: repo2
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 300Mi
      # this stuff is for the "pgbackrest" container (the only non-init container) in the "obps-postgres-repo-host" pod
      repoHost:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      sidecars:
        # this stuff is for the "pgbackrest" container in the "obps-postgres-pgha1" set of pods
        pgbackrest:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      # allows the triggering of manual backups
      manual:
        repoName: repo2
        options:
          - --type=full
  patroni:
    dynamicConfiguration:
      postgresql:
        # these will probably allow your database to start up, but you'll definitely want to tune them up a bit for anything but the most minimal DBs.
        parameters:
          shared_buffers: "128MB" # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
          wal_buffers: "-1" # automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
          min_wal_size: "32MB"
          max_wal_size: "500MB" # default is 1GB
